Db setup for ecommerce
imran-akhtar-brainx/ecommerce_project pull request #1
Opened 2022-11-25 15:36 UTC by imran-akhtar-brainx

2022-11-25 21:22 UTC, usama-javaid-brainx requested changes

2022-11-25 21:22 UTC, usama-javaid-brainx commented on app/models/category.rb
> +  has_many :sub_categories
use dependent destroy here as well

2022-11-25 21:22 UTC, usama-javaid-brainx commented on .idea/workspace.xml
> +  </component>
remove all idea files as these are the IDE configurations

2022-11-25 21:22 UTC, usama-javaid-brainx commented on db/migrate/20221125065738_create_products.rb
> +      t.belongs_to :sub_category
you didn't mention foreign_key here

2022-11-25 21:22 UTC, usama-javaid-brainx commented on app/models/sub_category.rb
> +  has_many :products
dependant destroy here as well

2022-11-25 21:22 UTC, usama-javaid-brainx commented on db/migrate/20221125070346_create_orders.rb
> +      t.integer :phone_number
phone number must be string

2022-11-25 21:22 UTC, usama-javaid-brainx commented on test/fixtures/categories.yml
> +# column: value
remove all the test files as we are not using it

2022-11-26 15:39 UTC, sobanakram approved these changes

2022-11-26 15:39 UTC, sobanakram commented on db/seeds.rb
> +Order.create(email: "imran.akhtar@gmail.com", customer_name: "imran", phone_number: 03340053857)
Use variables and use id through variable instead of static id 
Also, create around 5 sub categories and 10 products here.

2022-11-28 07:59 UTC, merged